/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GroupId = IDL.Nat;
export const UserId = IDL.Principal;
export const HangoutId = IDL.Nat;
export const MessageId = IDL.Nat;
export const PostId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'status' : MessageStatus,
  'content' : IDL.Text,
  'recipient' : UserId,
  'sender' : UserId,
  'timestamp' : Time,
});
export const GroupChatView = IDL.Record({
  'id' : GroupId,
  'messages' : IDL.Vec(Message),
  'name' : IDL.Text,
  'memberIds' : IDL.Vec(UserId),
});
export const HangoutPostView = IDL.Record({
  'id' : HangoutId,
  'title' : IDL.Text,
  'maxSpots' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'approvedAttendees' : IDL.Vec(UserId),
  'author' : UserId,
  'location' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostType = IDL.Variant({
  'hangout' : IDL.Null,
  'regular' : IDL.Null,
  'story' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : PostId,
  'postType' : PostType,
  'content' : IDL.Opt(ExternalBlob),
  'author' : UserId,
  'timestamp' : Time,
  'caption' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
  'avatar' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
  'adminDeleteHangout' : IDL.Func([HangoutId], [], []),
  'adminDeleteMessage' : IDL.Func([MessageId], [], []),
  'adminDeletePost' : IDL.Func([PostId], [], []),
  'approveHangoutRequest' : IDL.Func([HangoutId, UserId], [], []),
  'approveMessage' : IDL.Func([MessageId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroupChat' : IDL.Func(
      [IDL.Text, IDL.Vec(UserId)],
      [GroupChatView],
      [],
    ),
  'createHangout' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Nat],
      [HangoutPostView],
      [],
    ),
  'createPost' : IDL.Func([IDL.Opt(ExternalBlob), IDL.Text], [Post], []),
  'declineMessage' : IDL.Func([MessageId], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'denyHangoutRequest' : IDL.Func([HangoutId, UserId], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroupChat' : IDL.Func([GroupId], [IDL.Opt(GroupChatView)], ['query']),
  'getHomeFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestJoinHangout' : IDL.Func([HangoutId], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendGroupMessage' : IDL.Func([GroupId, IDL.Text], [], []),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [Message], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GroupId = IDL.Nat;
  const UserId = IDL.Principal;
  const HangoutId = IDL.Nat;
  const MessageId = IDL.Nat;
  const PostId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'status' : MessageStatus,
    'content' : IDL.Text,
    'recipient' : UserId,
    'sender' : UserId,
    'timestamp' : Time,
  });
  const GroupChatView = IDL.Record({
    'id' : GroupId,
    'messages' : IDL.Vec(Message),
    'name' : IDL.Text,
    'memberIds' : IDL.Vec(UserId),
  });
  const HangoutPostView = IDL.Record({
    'id' : HangoutId,
    'title' : IDL.Text,
    'maxSpots' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'approvedAttendees' : IDL.Vec(UserId),
    'author' : UserId,
    'location' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostType = IDL.Variant({
    'hangout' : IDL.Null,
    'regular' : IDL.Null,
    'story' : IDL.Null,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'postType' : PostType,
    'content' : IDL.Opt(ExternalBlob),
    'author' : UserId,
    'timestamp' : Time,
    'caption' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGroupMember' : IDL.Func([GroupId, UserId], [], []),
    'adminDeleteHangout' : IDL.Func([HangoutId], [], []),
    'adminDeleteMessage' : IDL.Func([MessageId], [], []),
    'adminDeletePost' : IDL.Func([PostId], [], []),
    'approveHangoutRequest' : IDL.Func([HangoutId, UserId], [], []),
    'approveMessage' : IDL.Func([MessageId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroupChat' : IDL.Func(
        [IDL.Text, IDL.Vec(UserId)],
        [GroupChatView],
        [],
      ),
    'createHangout' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Nat],
        [HangoutPostView],
        [],
      ),
    'createPost' : IDL.Func([IDL.Opt(ExternalBlob), IDL.Text], [Post], []),
    'declineMessage' : IDL.Func([MessageId], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'denyHangoutRequest' : IDL.Func([HangoutId, UserId], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroupChat' : IDL.Func([GroupId], [IDL.Opt(GroupChatView)], ['query']),
    'getHomeFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestJoinHangout' : IDL.Func([HangoutId], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendGroupMessage' : IDL.Func([GroupId, IDL.Text], [], []),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [Message], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };