/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GroupChatView {
  'id' : GroupId,
  'messages' : Array<Message>,
  'name' : string,
  'memberIds' : Array<UserId>,
}
export type GroupId = bigint;
export type HangoutId = bigint;
export interface HangoutPostView {
  'id' : HangoutId,
  'title' : string,
  'maxSpots' : bigint,
  'date' : Time,
  'description' : string,
  'approvedAttendees' : Array<UserId>,
  'author' : UserId,
  'location' : string,
}
export interface Message {
  'id' : MessageId,
  'status' : MessageStatus,
  'content' : string,
  'recipient' : UserId,
  'sender' : UserId,
  'timestamp' : Time,
}
export type MessageId = bigint;
export type MessageStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface Post {
  'id' : PostId,
  'postType' : PostType,
  'content' : [] | [ExternalBlob],
  'author' : UserId,
  'timestamp' : Time,
  'caption' : string,
}
export type PostId = bigint;
export type PostType = { 'hangout' : null } |
  { 'regular' : null } |
  { 'story' : null };
export interface Profile {
  'bio' : string,
  'username' : string,
  'followers' : bigint,
  'following' : bigint,
  'avatar' : [] | [ExternalBlob],
}
export type Time = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGroupMember' : ActorMethod<[GroupId, UserId], undefined>,
  'adminDeleteHangout' : ActorMethod<[HangoutId], undefined>,
  'adminDeleteMessage' : ActorMethod<[MessageId], undefined>,
  'adminDeletePost' : ActorMethod<[PostId], undefined>,
  'approveHangoutRequest' : ActorMethod<[HangoutId, UserId], undefined>,
  'approveMessage' : ActorMethod<[MessageId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroupChat' : ActorMethod<[string, Array<UserId>], GroupChatView>,
  'createHangout' : ActorMethod<
    [string, string, Time, string, bigint],
    HangoutPostView
  >,
  'createPost' : ActorMethod<[[] | [ExternalBlob], string], Post>,
  'declineMessage' : ActorMethod<[MessageId], undefined>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'denyHangoutRequest' : ActorMethod<[HangoutId, UserId], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getAllUsers' : ActorMethod<[], Array<UserId>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroupChat' : ActorMethod<[GroupId], [] | [GroupChatView]>,
  'getHomeFeed' : ActorMethod<[], Array<Post>>,
  'getProfile' : ActorMethod<[UserId], [] | [Profile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestJoinHangout' : ActorMethod<[HangoutId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'sendGroupMessage' : ActorMethod<[GroupId, string], undefined>,
  'sendMessage' : ActorMethod<[UserId, string], Message>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];